### ISSUE TITLE
Can't login

### ISSUE THREAD

**Issue by Preventlow** [tillsteinbach/WeConnect-cli#102]
Hello,

I'm getting the following error messages when trying to get info about my ID.3 using latest version of WeConnect-Cli. I've run the update which installed WeConnect 0.54, but that didn't help. Running macOS 12.6.3.

Traceback (most recent call last):
  File "/Users/zzz/Library/Python/3.9/bin/weconnect-cli", line 8, in <module>
    sys.exit(main())
  File "/Users/zzz/Library/Python/3.9/lib/python/site-packages/weconnect_cli/weconnect_cli_base.py", line 209, in main
    weConnect.login()
  File "/Users/zzz/Library/Python/3.9/lib/python/site-packages/weconnect/weconnect.py", line 182, in login
    self.__session.login()
  File "/Users/zzz/Library/Python/3.9/lib/python/site-packages/weconnect/auth/we_connect_session.py", line 75, in login
    authorizationUrl = self.authorizationUrl(url='https://identity.vwgroup.io/oidc/v1/authorize')
  File "/Users/zzz/Library/Python/3.9/lib/python/site-packages/weconnect/auth/we_connect_session.py", line 96, in authorizationUrl
    redirect = tryLoginResponse.headers['Location']
  File "/Users/zzz/Library/Python/3.9/lib/python/site-packages/requests/structures.py", line 52, in __getitem__
    return self._store[key.lower()][1]
KeyError: 'location'

**Comment by tillsteinbach** [comment]
URLs in the API changed. Will fix it tomorrow.

**Comment by Preventlow** [comment]
Thank you so much!

**Comment by Preventlow** [comment]
@tillsteinbach I can confirm that the new version of WeConnect-Cli works again. Thank you so much for the quick fix and for your great work!

**Comment by monojk** [comment]
Is it available now? I still get the error. I did a `pip3 install weconnect-cli --upgrade`

**Comment by tillsteinbach** [comment]
You don’t see the update because python 3.7 support was dropped some months ago. You need to install at least python 3.8.

**Comment by monojk** [comment]
Thanks, it works with Python3.9 now.
Btw as a heads up, I installed Python3.11 first but got an error in the PIL (pillow) component while running  `pip3 install weconnect-cli --upgrade` complaining about a missing configuration file in pillow (I can't remember which).

**Comment by Sh0n** [comment]
Any chances to add compatibility with python 3.7 for those we use weconnect-cli on Raspberry Buster ? :)

**Comment by tillsteinbach** [comment]
What is the problem with python 3.8 on raspberry?

**Comment by Sh0n** [comment]
Unless I am mistaken, in Debian 10 (Buster) the latest version available with simple command (like apt-get install python3) is python 3.7

**Comment by tillsteinbach** [comment]
Ah, ok. Yes, single command is not possible, but there are nice scripts like this one: https://itheo.tech/install-python-38-on-a-raspberry-pi

**Comment by gerhard1951** [comment]
Many thanks for your immediate update. Unfortunately it does not work in my case. Originally I worked with python 3.7. Then I updated to python 3.8 using the (useful) script you mentioned above. But weconnect-cli is still not working. The commands "pip3 install weconnect-cli" and "pip3 install weconnect-cli ---upgrade" run without any warning. Do you have an idea what could be wrong?
[logfile pip3 install weconnect-cli.txt](https://github.com/tillsteinbach/WeConnect-cli/files/10859293/logfile.pip3.install.weconnect-cli.txt)

**Comment by tillsteinbach** [comment]
that looks fine. What does `weconnect-cli --version` say?

**Comment by gerhard1951** [comment]
Surprising:  weconnect-cli 0.33.4 (using WeConnect-python 0.49.0)
Using "pip3 install weconnect-cli --upgrade" didnt't change anything. Still same version.

**Comment by tillsteinbach** [comment]
then you probably have still python3.7 as your default version. You can check with `python --version`

**Comment by gerhard1951** [comment]
pi@raspberrypi:~ $ python --version
Python 3.8.0
pi@raspberrypi:~ $

**Comment by tillsteinbach** [comment]
somehow it is still trying to use your old weconnect-cli installation. What does `which weconnect-cli` say?

**Comment by gerhard1951** [comment]
***@***.***:~ $ which weconnect-cli

/home/pi/.local/bin/weconnect-cli

***@***.***:~ $

 

Von: Till Steinbach ***@***.***> 
Gesendet: Mittwoch, 1. März 2023 11:10
An: tillsteinbach/WeConnect-cli ***@***.***>
Cc: gerhard1951 ***@***.***>; Comment ***@***.***>
Betreff: Re: [tillsteinbach/WeConnect-cli] Can't login (Issue #102)

 

somehow it is still trying to use your old weconnect-cli installation. What does which weconnect-cli say?

**Comment by gerhard1951** [comment]
pi@raspberrypi:~ $ which weconnect-cli
/home/pi/.local/bin/weconnect-cli
pi@raspberrypi:~ $

**Comment by essjmcb** [comment]
Hi!
I also have problems upgrading weconnect-cli with "pip3 install weconnect-cli ---upgrade" command. 
I can't say what's going on looking at the logs (attached). The new package is downloaded but the installation fails.

My current weconnect-cli version is "weconnect-cli 0.33.3 (usingWeConnect-python0.48.3)". I need to upgrade due to the same access problem. I am using Python ver3.9.

Thanks!
[failed_weconnect_upgrade.txt](https://github.com/tillsteinbach/WeConnect-cli/files/10860153/failed_weconnect_upgrade.txt)

**Comment by essjmcb** [comment]
Hi again!
Problem solved. I had to reinstall Pydroid3 (weconnect-cli running over Android). 
Now working as before.
Thanks!

**Comment by gerhard1951** [comment]
Problem solved! After using the command line to key-in a command I got the request to agree (again) to "... terms and conditions... " at the "myvolkswagen" homepage. I did this and everything runs as usual. Sorry for the confusion.

**Comment by Sh0n** [comment]
> Ah, ok. Yes, single command is not possible, but there are nice scripts like this one: https://itheo.tech/install-python-38-on-a-raspberry-pi

Thanks but I can't do this, all my system depend to Python 2.7 so I can't simply update python easily.
Is a lot of differences bewteen lastest python2.7 compatible version and lastest version python3 compatible ?

Any chance to re-add python 2.7 compatibility in your roadmap ?

**Comment by tillsteinbach** [comment]
I definitely won’t have time for that, sorry. But you can install several python versions in parallel.

**Comment by Sh0n** [comment]
ok, I understand, I will deal with it, and try another solution.

Another question, I have the feeling that when we use password with specials caracters, login failed with message "CRITICAL:There was a problem when authenticating with WeConnect: Password is invalid". 

Any idea about that ? there is escape character to use ?

Thanks !

**Comment by tillsteinbach** [comment]
yes, probably some characters need to be escaped.

**Comment by gerhard1951** [comment]
Hi,
since yesterday evening my weconnect-cli does not work any longer. Sending the command (which worked up to now)

"weconnect-cli --username xxxx@xxxxxxxxx.de --password xxxxxxxxx get /vehicles/WVWXXXXXXXXX/domains/charging/batteryStatus/currentSOC_pct"
 I get the response:
"023-03-16T16:16:53+0100:CRITICAL:There was a problem when communicating with WeConnect: Status Code from WeConnect while refreshing tokens was: 400".

What might be the reason for this mentioned error?

My actual version:   sudo weconnect-cli --version 
weconnect-cli 0.33.9 (using WeConnect-python 0.54.2)"
Thanks for your help
gerhard

**Comment by essjmcb** [comment]
Hi,
I have the same problem.
I am using weconnect-cli 0.33.8 (using WeConnect-python 0.54.1).
Thanks.
BR/ Juan

**Comment by essjmcb** [comment]
I do not get any terms and conditions acceptance request when login to myVolkswagen. Shall I login to a different site?
Thanks.

**Comment by gerhard1951** [comment]
Same for me. This time no terms and conditions or similar to confirm at "www.volkswagen.de/de/besitzer-und-nutzer/myvolkswagen.html/__app/detailxxxxx".

**Comment by tillsteinbach** [comment]
Can you try logging out and on again inside the WeConnect ID app?

**Comment by essjmcb** [comment]
I logged out and in again with WeConnect ID app. Same error:
1772/domains/vehicleHealthInspection/maintenanceStatus/mileage_km             <
2023-03-16T18:59:13+0100:CRITICAL:There was a problem when communicating with WeConnect: Status Code from WeConnect while refreshing tokens was: 400
Thanks!

**Comment by tillsteinbach** [comment]
And if you delete the token file on your harddrive?

**Comment by monojk** [comment]
I also had the problem. It is gone after rebooting my raspberry where I run the command from....

**Comment by essjmcb** [comment]
A restart on my Android phone did not help.

**Comment by tillsteinbach** [comment]
It is stored on the hardisk. You can see the path when you use the `—help` option. The token is obtained after login and used between several requests. It prevents that you log in every time you use weconnect-cli

**Comment by gerhard1951** [comment]
... deleting "weconnect.token" helped. Now weconnect-cli works again as usual. But what is the reason that deleting of "weconect.token" became necessary?
Anyway, Till, thanks again for your great help

Gerhard

**Comment by tillsteinbach** [comment]
Seems the server did not like the token that was invalidated on server side. I will add that in such a case a new login is tried.

**Comment by essjmcb** [comment]
Also fixed here removing the token file.
Many thanks for your support.
