### ISSUE TITLE
Cannot refresh token

### ISSUE THREAD

**Issue by waxipedia** [tillsteinbach/WeConnect-cli#150]
The tool always worked properly but in the last days I receive following error:

weconnect-cli --username myname@somedomain.de --password TOPSCRET get /vehicles/MYVID/domains/charging/batteryStatus/currentSOC_pct

2024-11-30T16:52:42+0100:ERROR:Retrieval Error while refreshing token. Probably the token was invalidated. Trying to do a new login instead.
Traceback (most recent call last):
  File "/home/pi/.local/lib/python3.9/site-packages/weconnect/auth/openid_session.py", line 194, in request
    url, headers, data = self.addToken(url, body=data, headers=headers, access_type=access_type, token=token)
  File "/home/pi/.local/lib/python3.9/site-packages/weconnect/auth/openid_session.py", line 242, in addToken
    raise TokenExpiredError()
oauthlib.oauth2.rfc6749.errors.TokenExpiredError: (token_expired) 

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/pi/.local/lib/python3.9/site-packages/weconnect/auth/openid_session.py", line 200, in request
    self.refresh()
  File "/home/pi/.local/lib/python3.9/site-packages/weconnect/auth/we_connect_session.py", line 82, in refresh
    self.refreshTokens(
  File "/home/pi/.local/lib/python3.9/site-packages/weconnect/auth/we_connect_session.py", line 361, in refreshTokens
    raise RetrievalError(f'Status Code from WeConnect while refreshing tokens was: {tokenResponse.status_code}')
weconnect.errors.RetrievalError: Status Code from WeConnect while refreshing tokens was: 400

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/pi/.local/bin/weconnect-cli", line 8, in <module>
    sys.exit(main())
  File "/home/pi/.local/lib/python3.9/site-packages/weconnect_cli/weconnect_cli_base.py", line 240, in main
    weConnect.update(updateCapabilities=(not args.noCapabilities), updatePictures=(not args.noPictures), selective=args.selective)
  File "/home/pi/.local/lib/python3.9/site-packages/weconnect/weconnect.py", line 194, in update
    self.updateVehicles(updateCapabilities=updateCapabilities, updatePictures=updatePictures, force=force, selective=selective)
  File "/home/pi/.local/lib/python3.9/site-packages/weconnect/weconnect.py", line 205, in updateVehicles
    data = self.fetchData(url, force)
  File "/home/pi/.local/lib/python3.9/site-packages/weconnect/weconnect.py", line 373, in fetchData
    statusResponse: requests.Response = self.session.get(url, allow_redirects=False)
  File "/home/pi/.local/lib/python3.9/site-packages/requests/sessions.py", line 602, in get
    return self.request("GET", url, **kwargs)
  File "/home/pi/.local/lib/python3.9/site-packages/weconnect/auth/we_connect_session.py", line 69, in request
    return super(WeConnectSession, self).request(
  File "/home/pi/.local/lib/python3.9/site-packages/weconnect/auth/openid_session.py", line 209, in request
    self.login()
  File "/home/pi/.local/lib/python3.9/site-packages/weconnect/auth/we_connect_session.py", line 76, in login
    response = self.doWebAuth(authorizationUrl)
  File "/home/pi/.local/lib/python3.9/site-packages/weconnect/auth/we_connect_session.py", line 253, in doWebAuth
    afterLoginResponse = self.get(afterLoginUrl, allow_redirects=False, access_type=AccessType.NONE)
  File "/home/pi/.local/lib/python3.9/site-packages/requests/sessions.py", line 602, in get
    return self.request("GET", url, **kwargs)
  File "/home/pi/.local/lib/python3.9/site-packages/weconnect/auth/we_connect_session.py", line 69, in request
    return super(WeConnectSession, self).request(
  File "/home/pi/.local/lib/python3.9/site-packages/weconnect/auth/openid_session.py", line 188, in request
    raise InsecureTransportError()
oauthlib.oauth2.rfc6749.errors.InsecureTransportError: (insecure_transport) OAuth 2 MUST utilize https.

**Comment by tillsteinbach** [comment]
Please logout in the VW app and in again. It will ask you to accept new terms and conditions.

**Comment by waxipedia** [comment]
You saved my day. Your tool has been working more than a year without any issue that I forgot this nasty fact. Maybe you can add a few lines in the documentation and in the error message.

**Comment by tillsteinbach** [comment]
Yea, I had that in, but VW changed the backend and now my check does not work anymore. I will fix that, but it will require people to update. So for the moment it does not help.
