### ISSUE TITLE
Assistance Required for WeConnect-CLI Error (InsecureTransportError)

### ISSUE THREAD

**Issue by Eddy7823** [tillsteinbach/WeConnect-cli#152]
Hi

I’m encountering an issue while using weconnect-cli. When trying to retrieve the current target SOC (State of Charge) for a vehicle, I receive the following error:

PC192-168-10-10:~ eduard$ weconnect-cli --username schmidteduard@me.com --password ......  get /vehicles/WV2.../domains/charging/chargingSettings/targetSOC_pct
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.13/bin/weconnect-cli", line 8, in <module>
    sys.exit(main())
             ~~~~^^
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/weconnect_cli/weconnect_cli_base.py", line 205, in main
    weConnect.login()
    ~~~~~~~~~~~~~~~^^
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/weconnect/weconnect.py", line 184, in login
    self.__session.login()
    ~~~~~~~~~~~~~~~~~~~~^^
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/weconnect/auth/we_connect_session.py", line 76, in login
    response = self.doWebAuth(authorizationUrl)
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/weconnect/auth/we_connect_session.py", line 253, in doWebAuth
    afterLoginResponse = self.get(afterLoginUrl, allow_redirects=False, access_type=AccessType.NONE)
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/requests/sessions.py", line 602, in get
    return self.request("GET", url, **kwargs)
           ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/weconnect/auth/we_connect_session.py", line 69, in request
    return super(WeConnectSession, self).request(
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        method, url, headers=headers, data=data, withhold_token=withhold_token, access_type=access_type, token=token, timeout=timeout, **kwargs
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/weconnect/auth/openid_session.py", line 188, in request
    raise InsecureTransportError()
**oauthlib.oauth2.rfc6749.errors.InsecureTransportError: (insecure_transport) OAuth 2 MUST utilize https.**
PC192-168-10-10:~ eduard$ python3 --version
Python 3.13.1
PC192-168-10-10:~ eduard$ weconnect-cli --version
weconnect-cli 0.38.7 (using WeConnect-python 0.60.5)
PC192-168-10-10:~ eduard$

**Comment by tillsteinbach** [comment]
You need to accept the new terms and conditions of VW. Easiest way is to log out and in again in the VW app.

**Comment by Eddy7823** [comment]
Hi,

Thank you so much for the quick and helpful response! Logging out and back in via the VW app to accept the new terms and conditions resolved the issue perfectly.

Now, it’s just a matter of time and effort to properly link the GUI to the functionality.

I appreciate your support and guidance!

![image](https://github.com/user-attachments/assets/ebfaebbe-c493-4c91-831f-c30c1b8df097)

**Comment by waberc** [comment]
Hi @tillsteinbach I have the same issue when using the home-assistant integration using your library and could reproduce it with the command line tool (without home-assistant) as well.

But when logging out from the app and in again, I don't get any "please accept the terms and conditions" pop-up. Neither when going to the section "synchronize now" which opens a web view inside the app.

I also tried on their webpage where everything seems allowed: https://id.vwgroup.io/account

![Capture d’écran 2024-12-04 à 22 16 35](https://github.com/user-attachments/assets/d45dc894-ef89-4080-b80e-afc14d92118e)

Do you have more hints were I could bring up the terms and conditions re-acceptance ?

**Comment by geblabs** [comment]
Same issue here.

Logging out from "https://id.vwgroup.io/account" and in again, I always get "please accept the terms and conditions" and accepting dont makes any difference, I get "please accept the terms and conditions" anyway at next login.

**Comment by markussc** [comment]
Same issue here as well. Logged in and out several times from the website and app. The strange thing is that I'm asked every time to accept the terms and conditions...

**Comment by vellukoo** [comment]
Same issue here.

Any news about this?

**Comment by markussc** [comment]
I could solve the underlying problem according to https://github.com/mitch-dc/volkswagen_we_connect_id/issues/285

**Comment by geblabs** [comment]
I could solve me too. In brief: on "https://id.vwgroup.io/account" switch to another country, logout, login, accept eula, logout, login, switch to real country, logout, login, eventually accept eula.
