### ISSUE TITLE
Exception ObserverPriority

### ISSUE THREAD

**Issue by mdhom** [tillsteinbach/WeConnect-cli#2]
I had the cli running with the `events` command and got the following exception:
```
Traceback (most recent call last):
  File "c:\python39\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\python39\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\MaxDhom\AppData\Roaming\Python\Python39\Scripts\weconnect-cli.exe\__main__.py", line 7, in <module>
  File "C:\Users\MaxDhom\AppData\Roaming\Python\Python39\site-packages\weconnect_cli\weconnect_cli.py", line 208, in main
    weConnect.update()
  File "C:\Users\MaxDhom\AppData\Roaming\Python\Python39\site-packages\weconnect\weconnect.py", line 415, in update
    self.__vehicles[vin].update(fromDict=vehicleDict, updateCapabilities=updateCapabilities)
  File "C:\Users\MaxDhom\AppData\Roaming\Python\Python39\site-packages\weconnect\elements.py", line 117, in update
    self.updateStatus(updateCapabilities=updateCapabilities, force=force)
  File "C:\Users\MaxDhom\AppData\Roaming\Python\Python39\site-packages\weconnect\elements.py", line 154, in updateStatus
    self.statuses[key].update(fromDict=data['data'][key])
  File "C:\Users\MaxDhom\AppData\Roaming\Python\Python39\site-packages\weconnect\elements.py", line 1148, in update
    self.targetTemperature_K.setValueWithCarTime(
  File "C:\Users\MaxDhom\AppData\Roaming\Python\Python39\site-packages\weconnect\addressable.py", line 174, in setValueWithCarTime
    self.notify(flags)
  File "C:\Users\MaxDhom\AppData\Roaming\Python\Python39\site-packages\weconnect\addressable.py", line 49, in notify
    observers = self.getObservers(flags)
  File "C:\Users\MaxDhom\AppData\Roaming\Python\Python39\site-packages\weconnect\addressable.py", line 34, in getObservers
    return [observerEntry[0] for observerEntry in self.getObserverEntries(flags)]
  File "C:\Users\MaxDhom\AppData\Roaming\Python\Python39\site-packages\weconnect\addressable.py", line 46, in getObserverEntries
    return sorted(observers, key=lambda entry: entry[2])
TypeError: '<' not supported between instances of 'ObserverPriority' and 'ObserverPriority'
```

**Comment by tillsteinbach** [comment]
Ouch, yes this is a bug. I‘ll try to fix that as fast as possible.
I‘ll definitely need to find some time to implement some automated testing.

**Comment by mdhom** [comment]
awesome! thanks for your efforts!
________________________________

**Comment by tillsteinbach** [comment]
Can you check if version 0.6.1 I just pushed fixes your problem and if not open the bug again? Thanks for reporting!
