### ISSUE TITLE
Getting data fails

### ISSUE THREAD

**Issue by jochenpee** [tillsteinbach/WeConnect-cli#6]
This is what I just got:

Traceback (most recent call last):
  File "/usr/local/bin/wc-cli", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.8/site-packages/weconnect_cli/weconnect_cli.py", line 158, in main
    weConnect.update()
  File "/usr/local/lib/python3.8/site-packages/weconnect/weconnect.py", line 414, in update
    vehicle = Vehicle(weConnect=self, vin=vin, parent=self.__vehicles, fromDict=vehicleDict,
  File "/usr/local/lib/python3.8/site-packages/weconnect/elements.py", line 49, in __init__
    self.update(fromDict)
  File "/usr/local/lib/python3.8/site-packages/weconnect/elements.py", line 146, in update
    self.updateStatus(updateCapabilities=updateCapabilities, force=force)
  File "/usr/local/lib/python3.8/site-packages/weconnect/elements.py", line 214, in updateStatus
    self.statuses[status] = keyClassMap[status](vehicle=self, parent=self.statuses, statusId=status,
KeyError: 'chargeMode'
Traceback (most recent call last):
  File "/usr/local/bin/wc-cli", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.8/site-packages/weconnect_cli/weconnect_cli.py", line 158, in main
    weConnect.update()
  File "/usr/local/lib/python3.8/site-packages/weconnect/weconnect.py", line 414, in update
    vehicle = Vehicle(weConnect=self, vin=vin, parent=self.__vehicles, fromDict=vehicleDict,
  File "/usr/local/lib/python3.8/site-packages/weconnect/elements.py", line 49, in __init__
    self.update(fromDict)
  File "/usr/local/lib/python3.8/site-packages/weconnect/elements.py", line 146, in update
    self.updateStatus(updateCapabilities=updateCapabilities, force=force)
  File "/usr/local/lib/python3.8/site-packages/weconnect/elements.py", line 214, in updateStatus
    self.statuses[status] = keyClassMap[status](vehicle=self, parent=self.statuses, statusId=status,
KeyError: 'chargeMode'

Any ideas?

**Comment by jochenpee** [comment]
Similar after this update:

Installing collected packages: weconnect, weconnect-cli
  Attempting uninstall: weconnect
    Found existing installation: weconnect 0.8.1
    Uninstalling weconnect-0.8.1:
      Successfully uninstalled weconnect-0.8.1
  Attempting uninstall: weconnect-cli
    Found existing installation: weconnect-cli 0.8.1
    Uninstalling weconnect-cli-0.8.1:
      Successfully uninstalled weconnect-cli-0.8.1
Successfully installed weconnect-0.11.1 weconnect-cli-0.10.2

**Comment by tillsteinbach** [comment]
Very interesting! Looks like the API got an update.
I'm on vacation right now but will push an update as soon as I'm back.

**Comment by tillsteinbach** [comment]
Will be covered in: https://github.com/tillsteinbach/WeConnect-python/issues/12

**Comment by tillsteinbach** [comment]
@jochenpee could you check if 0.11.3.dev1 fixes the Problem?

**Comment by msome** [comment]
Thank you @tillsteinbach , the 0.11.3.dev1 fixes the general data-access problem on my side, I got back my battery/door/range readings now.

**Comment by tillsteinbach** [comment]
Thanks for testing, then I will release the 0.11.3 tonight.

**Comment by tillsteinbach** [comment]
0.11.3 released
