### ISSUE TITLE
KeyError: 'car_birdview'

### ISSUE THREAD

**Issue by jochenpee** [tillsteinbach/WeConnect-cli#9]
Traceback (most recent call last):
  File "/usr/local/bin/wc-cli", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.8/site-packages/weconnect_cli/weconnect_cli.py", line 185, in main
    weConnect.update(updateCapabilities=(not args.noCapabilities), updatePictures=(not args.noPictures))
  File "/usr/local/lib/python3.8/site-packages/weconnect/weconnect.py", line 419, in update
    self.updateVehicles(updateCapabilities=updateCapabilities, updatePictures=updatePictures, force=force)
  File "/usr/local/lib/python3.8/site-packages/weconnect/weconnect.py", line 457, in updateVehicles
    vehicle = Vehicle(weConnect=self, vin=vin, parent=self.__vehicles, fromDict=vehicleDict,
  File "/usr/local/lib/python3.8/site-packages/weconnect/elements/vehicle.py", line 67, in __init__
    self.update(fromDict, updateCapabilities=updateCapabilities, updatePictures=updatePictures)
  File "/usr/local/lib/python3.8/site-packages/weconnect/elements/vehicle.py", line 167, in update
    self.updatePictures()
  File "/usr/local/lib/python3.8/site-packages/weconnect/elements/vehicle.py", line 389, in updatePictures
    self.updateStatusPicture()
  File "/usr/local/lib/python3.8/site-packages/weconnect/elements/vehicle.py", line 392, in updateStatusPicture
    img = self.__carImages['car_birdview']
KeyError: 'car_birdview'

**Comment by tillsteinbach** [comment]
I will investigate that as soon as possible. As a work-around you may want to check the parameter --no-pictures

**Comment by jochenpee** [comment]
Works, thanks! Do not need pictures, anyway.

**Comment by tillsteinbach** [comment]
Yea, I think this is true for most. I might turn the option around to opt-in for pictures. Will save some requests.

**Comment by tillsteinbach** [comment]
Should be fixed in 0.13.2 that I just released.
